# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 946f02fa90afdada65bc6db8a5bdaef36cd2e88d2328e1e6ae2a1cea6ca6f746abda4f3a44d5a93bbceb8d150f683fa46904b75382ed21c7f7c06aed81f0d9b3

test:
  secret_key_base: a6df2efe3959ba2949da6b173d2d0281a7a7b34df776a9c03cc95871dc2ee71d88abeaa6ac87bb78d6f53e96742757a4c40056693ad4f6627476e04a604d7fcc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
